"""Analytics Record domain model — the immutable metrics of one agent call.

A child entity of the Run aggregate root, owned **through its Task** (DOMAIN_MODEL.md §2.15, §9.1):
one append-only record per call — provider and model, input/output tokens, cost, execution time and
the step's retry count (PROJECT.md §16) — the factual base the Analytics Agent will aggregate. It is
created only via ``Run.record_analytics`` and never changes afterwards: there is no update or
delete, and its single state ``Recorded`` is implicit in its existence (ADR-0020 §3).

The metric values are Value Objects (DOMAIN_MODEL.md §11) — ``TokenUsage``, ``Cost``, ``TimeRange``
— validated on construction, so an implausible measurement never reaches the Run. The domain never
reads the clock or computes a price: both are measured outside and passed in (ADR-0020 §2).

This module depends only on stdlib and ``domain.errors``; its references (``run_id``, ``task_id``,
``agent_ref``) are opaque ``str`` (ADR-0003 §3), avoiding any import cycle.

Scope note (ADR-0020): capturing a record on every real call (the LLM port does not report usage
yet), aggregation, the Analytics Adapter/Agent, the call outcome and retention are deferred.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from decimal import Decimal
from typing import TypeAlias

from omemo_content_factory.domain.errors import DomainError

AnalyticsRecordId: TypeAlias = str
"""Opaque, stable identifier of an Analytics Record (ADR-0020 §3). Generated by the owning Run."""


# --- Value Objects -----------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class TokenUsage:
    """Input/output tokens of one call — a Value Object (DOMAIN_MODEL.md §11; ADR-0020 §2)."""

    input_tokens: int
    output_tokens: int

    def __post_init__(self) -> None:
        _require_count("input_tokens", self.input_tokens)
        _require_count("output_tokens", self.output_tokens)

    @property
    def total_tokens(self) -> int:
        """Input plus output tokens."""
        return self.input_tokens + self.output_tokens


@dataclass(frozen=True, slots=True)
class Cost:
    """The monetary cost of one call — a Value Object (DOMAIN_MODEL.md §11; ADR-0020 §2).

    ``amount`` is a finite, non-negative ``Decimal`` — never a ``float``, so thousands of records
    add up exactly — in ``currency`` (an opaque code such as ``"USD"``; there is no default). The
    price is computed outside the domain from the provider's rates; the domain keeps the result.
    """

    amount: Decimal
    currency: str

    def __post_init__(self) -> None:
        if not isinstance(self.amount, Decimal) or not self.amount.is_finite() or self.amount < 0:
            raise InvalidAnalyticsRecordError(
                f"cost amount must be a finite, non-negative Decimal, got {self.amount!r}"
            )
        if not self.currency.strip():
            raise InvalidAnalyticsRecordError("cost currency must not be blank")


@dataclass(frozen=True, slots=True)
class TimeRange:
    """When one call started and finished — a Value Object (DOMAIN_MODEL.md §11; ADR-0020 §2).

    Both moments are timezone-aware, so records stay comparable across hosts and over time
    (PROJECT.md §16), and ``finished_at`` is not before ``started_at``. The range is also the
    record's time mark (ADR-0020 §3).
    """

    started_at: datetime
    finished_at: datetime

    def __post_init__(self) -> None:
        for name, moment in (("started_at", self.started_at), ("finished_at", self.finished_at)):
            if moment.utcoffset() is None:
                raise InvalidAnalyticsRecordError(f"{name} must be timezone-aware, got {moment!r}")
        if self.finished_at < self.started_at:
            raise InvalidAnalyticsRecordError("a call cannot finish before it started")

    @property
    def duration(self) -> timedelta:
        """The execution time (latency) of the call."""
        return self.finished_at - self.started_at


# --- Analytics Record entity -------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class AnalyticsRecord:
    """The metrics of one agent call inside a Run (ADR-0020 §3).

    Immutable by construction (frozen), so it is exposed directly (read-only) through the Run root,
    like ``Output``; no snapshot view is needed. ``run_id``, ``task_id``, ``agent_ref`` and
    ``retries`` are derived by Run from the owned Task, so a record never contradicts it (§4).
    """

    record_id: AnalyticsRecordId
    run_id: str
    task_id: str
    agent_ref: str
    provider: str
    model: str
    token_usage: TokenUsage
    cost: Cost
    time_range: TimeRange
    retries: int
    prompt_ref: str | None = None

    def __post_init__(self) -> None:
        for name, value in (("provider", self.provider), ("model", self.model)):
            if not value.strip():
                raise InvalidAnalyticsRecordError(f"{name} must not be blank")
        if self.prompt_ref is not None and not self.prompt_ref.strip():
            raise InvalidAnalyticsRecordError("prompt_ref must not be blank when given")
        _require_count("retries", self.retries)


# --- Domain events -----------------------------------------------------------------------
# Recorded in the owning Run's existing event log (ADR-0020 §6).


@dataclass(frozen=True, slots=True)
class AnalyticsEvent:
    """Base type for Analytics Record domain events. Carries the owning Run id and the record id."""

    run_id: str
    record_id: str


@dataclass(frozen=True, slots=True)
class AnalyticsRecordCaptured(AnalyticsEvent):
    """Emitted when a call's metrics are recorded (DOMAIN_MODEL.md §10).

    Names the call's Task and role; the metrics themselves are read from the record.
    """

    task_id: str
    agent_ref: str


# --- Domain errors -----------------------------------------------------------------------
# Rooted at the shared ``DomainError`` (ADR-0017). Actor authorisation reuses Run's
# UnauthorizedActorError; immutability comes from the frozen dataclasses (ADR-0020 §7).


class AnalyticsDomainError(DomainError):
    """Base class for all Analytics Record domain-rule violations."""


class InvalidAnalyticsRecordError(AnalyticsDomainError):
    """A metric value is implausible, or the call it describes cannot have happened (ADR-0020 §7).

    Raised by the Value Objects on construction (negative or ``bool`` token counts; a negative,
    ``float`` or non-finite cost; a blank currency; a naive or reversed time range), by the record
    for a blank provider / model / prompt reference, and by Run for a Task that was never started.
    """


def _require_count(name: str, value: int) -> None:
    """Refuse a count that is negative or a ``bool`` (an ``int`` subclass, but not a count)."""
    if isinstance(value, bool) or value < 0:
        raise InvalidAnalyticsRecordError(f"{name} must be a non-negative int, got {value!r}")
