"""Artifact domain model — a unit of produced content of a Run.

A child entity of the Run aggregate root, owned **directly by Run** (DOMAIN_MODEL.md §2.12,
§9.1), carrying provenance to the ``Output`` it was produced from. It is created only via
``Run.create_artifact`` / ``Run.create_artifact_version`` (each from an existing Output), is
**1:1** with that Output, and is **immutable except for its own status lifecycle**. There is no
aggregate-driving factory here.

This module has no dependency on ``run``/``task``/``output`` (``run`` imports from it), so its
references (``run_id``, ``output_ref``) are plain opaque ``str`` (ADR-0003 §3) — also avoiding an
import cycle.

Lifecycle scope. The full documented lifecycle (DOMAIN_MODEL.md §2.12) is wired in three additive
steps: ``DRAFT -> CANDIDATE`` (ADR-0006); ``CANDIDATE -> APPROVED``/``REJECTED`` and
``APPROVED -> PUBLISHED`` (ADR-0007, gated by Human Review and — since ADR-0018 — by a passing QA
Evaluation); and every working state ``-> SUPERSEDED`` (ADR-0019, the rework path). A fixed version
is immutable: a rework produces a **new Artifact** (``version`` + 1, ``supersedes_ref`` pointing at
its predecessor) via ``Run.create_artifact_version``, which supersedes the predecessor in the same
operation. Output -> Artifact stays 1:1, so each version has its own Output provenance.

Deferred (ADR-0006): Output -> Artifact 1:N; flags/remarks on the Artifact itself.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TypeAlias

from omemo_content_factory.domain.errors import DomainError

ArtifactId: TypeAlias = str
"""Opaque, stable identifier of an Artifact (ADR-0006 §3). Generated by the owning Run."""


class ArtifactStatus(Enum):
    """The six lifecycle states of an Artifact (DOMAIN_MODEL.md §2.12).

    An Artifact is created ``DRAFT`` and moves ``DRAFT -> CANDIDATE -> APPROVED -> PUBLISHED``
    (ADR-0006 §4, ADR-0007 §6), ``CANDIDATE -> REJECTED``, or — from any **working** state, when a
    new version of it is produced — to ``SUPERSEDED`` (ADR-0019 §3). ``PUBLISHED``, ``REJECTED``
    and ``SUPERSEDED`` are terminal.
    """

    DRAFT = "draft"
    CANDIDATE = "candidate"
    APPROVED = "approved"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"
    PUBLISHED = "published"


# --- Read-only snapshot ------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ArtifactView:
    """Immutable, read-only snapshot of an Artifact (ADR-0006 §2).

    The only representation that leaves the aggregate: no mutable Artifact object is exposed, so
    a child changes only through its Run. A snapshot is point-in-time. ``supersedes_ref`` is the
    previous version this Artifact replaces, or ``None`` for a first version (ADR-0019 §2).
    """

    artifact_id: ArtifactId
    run_id: str
    output_ref: str
    kind: str
    content: str
    version: int
    status: ArtifactStatus
    supersedes_ref: str | None = None


# --- Domain events -----------------------------------------------------------------------
# Recorded in the owning Run's existing event log (ADR-0006 §8).


@dataclass(frozen=True, slots=True)
class ArtifactEvent:
    """Base type for Artifact domain events. Carries the owning Run id and the Artifact id."""

    run_id: str
    artifact_id: str


@dataclass(frozen=True, slots=True)
class ArtifactCreated(ArtifactEvent):
    """Emitted when an Artifact is created from an Output (DOMAIN_MODEL.md §10).

    Carries the provenance (``output_ref``) and the artifact ``kind``. A **new version** produced by
    rework emits the same event (no further Artifact event is documented, ADR-0019 §5): ``version``
    and ``supersedes_ref`` then make the supersession traceable in the Run log. Both default to a
    first version, so the event is unchanged for existing callers.
    """

    output_ref: str
    kind: str
    version: int = 1
    supersedes_ref: str | None = None


# --- Domain errors -----------------------------------------------------------------------
# Artifact domain-rule violations (ADR-0006 §9). Rooted at the shared ``DomainError``
# (ADR-0017). Actor authorisation reuses Run's UnauthorizedActorError.


class ArtifactDomainError(DomainError):
    """Base class for all Artifact domain-rule violations."""


class InvalidArtifactTransitionError(ArtifactDomainError):
    """A requested Artifact status transition is not allowed (ADR-0006 §4)."""


class DuplicateArtifactError(ArtifactDomainError):
    """A second Artifact was requested from an Output that already produced one (1:1)."""


class ArtifactNotApprovedError(ArtifactDomainError):
    """An Artifact was moved to ``APPROVED`` without an approving Human Review (ADR-0007 §6).

    Enforces the invariant "no ``Published`` without ``Approve``" (DOMAIN_MODEL.md §6): the gate
    is checked by the Run root before the transition; the Artifact entity stays unaware of reviews.
    """


class ArtifactQaNotPassedError(ArtifactDomainError):
    """An Artifact was moved to ``APPROVED`` without a passing latest QA Evaluation (ADR-0018 §5).

    Enforces the fail-closed invariant "risk -> content not further" (DOMAIN_MODEL.md §6): no
    evaluation, a ``PENDING`` one or a ``FLAGGED``/``FAILED`` latest verdict keeps the gate shut,
    even after a human ``Approve``. Checked by the Run root; the Artifact stays unaware of QA.
    """


class ArtifactSupersessionError(ArtifactDomainError):
    """``SUPERSEDED`` was requested without a new version replacing the Artifact (ADR-0019 §4).

    Enforces the invariant "a fixed Artifact version is immutable; an edit is a new version"
    (DOMAIN_MODEL.md §6): an Artifact is superseded **only** as the other half of creating its
    successor (``Run.create_artifact_version``), never by a bare status change — which would leave a
    Run with no live version of its content. Checked by the Run root.
    """


class ImmutableArtifactAttributeError(ArtifactDomainError):
    """An attempt was made to change an immutable attribute of an Artifact (everything but status).

    Guards the internal entity for parity with the Task reference implementation. Because Artifact
    is exposed only as an ``ArtifactView`` snapshot, this is a structural defence, not a path
    reachable through the public contract.
    """


# --- Allowed transitions -----------------------------------------------------------------

# Allowed Artifact status transitions (ADR-0006 §4; extended by ADR-0007 §6 with the publication
# path and by ADR-0019 §3 with the rework path "any working state -> SUPERSEDED",
# DOMAIN_MODEL.md §2.12). ``CANDIDATE -> APPROVED`` is additionally gated by the Run (an approving
# Human Review and a PASSED latest Evaluation must exist); ``-> SUPERSEDED`` is additionally gated
# by the Run (only ``create_artifact_version`` may take that edge).
_ALLOWED_ARTIFACT_TRANSITIONS: dict[ArtifactStatus, set[ArtifactStatus]] = {
    ArtifactStatus.DRAFT: {ArtifactStatus.CANDIDATE, ArtifactStatus.SUPERSEDED},
    ArtifactStatus.CANDIDATE: {
        ArtifactStatus.APPROVED,
        ArtifactStatus.REJECTED,
        ArtifactStatus.SUPERSEDED,
    },
    ArtifactStatus.APPROVED: {ArtifactStatus.PUBLISHED, ArtifactStatus.SUPERSEDED},
    ArtifactStatus.REJECTED: set(),
    ArtifactStatus.SUPERSEDED: set(),
    ArtifactStatus.PUBLISHED: set(),
}

# Immutable public attributes AND their private backing fields: everything except ``status``
# (ADR-0006 §2). Neither a public name nor its backing field may be reassigned after creation.
_IMMUTABLE_ARTIFACT_ATTRIBUTES = frozenset(
    {
        "artifact_id",
        "run_id",
        "output_ref",
        "kind",
        "content",
        "version",
        "supersedes_ref",
        "_artifact_id",
        "_run_id",
        "_output_ref",
        "_kind",
        "_content",
        "_version",
        "_supersedes_ref",
    }
)


# --- Artifact entity (internal — constructed only by Run) ---------------------------------


class Artifact:
    """The Artifact child entity — a unit of produced content of a Run (ADR-0006 §2).

    **Not** a public API: created only by ``Run.create_artifact`` and mutated (status only) by
    ``Run.transition_artifact``. ``__slots__`` + a guarded ``__setattr__`` make every field but
    ``status`` write-once, mirroring the Task reference implementation.
    """

    __slots__ = (
        "_artifact_id",
        "_content",
        "_kind",
        "_output_ref",
        "_run_id",
        "_status",
        "_supersedes_ref",
        "_version",
    )

    _artifact_id: ArtifactId
    _run_id: str
    _output_ref: str
    _kind: str
    _content: str
    _version: int
    _supersedes_ref: str | None
    _status: ArtifactStatus

    def __init__(
        self,
        artifact_id: ArtifactId,
        run_id: str,
        output_ref: str,
        kind: str,
        content: str,
        version: int,
        supersedes_ref: str | None = None,
    ) -> None:
        # Immutable fields are written exactly once, here, bypassing the guard below.
        object.__setattr__(self, "_artifact_id", artifact_id)
        object.__setattr__(self, "_run_id", run_id)
        object.__setattr__(self, "_output_ref", output_ref)
        object.__setattr__(self, "_kind", kind)
        object.__setattr__(self, "_content", content)
        object.__setattr__(self, "_version", version)
        object.__setattr__(self, "_supersedes_ref", supersedes_ref)
        # The status lifecycle is the only mutable state; it flows through the guarded setter.
        self._status = ArtifactStatus.DRAFT

    def __setattr__(self, name: str, value: object) -> None:
        """Reject reassignment of every attribute except ``status`` (ADR-0006 §2)."""
        if name in _IMMUTABLE_ARTIFACT_ATTRIBUTES:
            raise ImmutableArtifactAttributeError(f"'{name}' is immutable after creation")
        super().__setattr__(name, value)

    @classmethod
    def restore(cls, view: ArtifactView) -> Artifact:
        """Bring an Artifact back at its preserved status (called only by ``Run.restore``).

        The view holds every field of the entity, so no separate snapshot type is needed
        (RUN_RESTORE_SPEC §2). No transition is applied (ADR-0024).
        """
        artifact = cls(
            artifact_id=view.artifact_id,
            run_id=view.run_id,
            output_ref=view.output_ref,
            kind=view.kind,
            content=view.content,
            version=view.version,
            supersedes_ref=view.supersedes_ref,
        )
        artifact._status = view.status
        return artifact

    @property
    def output_ref(self) -> str:
        """Provenance: the id of the Output this Artifact was produced from."""
        return self._output_ref

    @property
    def view(self) -> ArtifactView:
        """A read-only snapshot of the current state (ADR-0006 §6)."""
        return ArtifactView(
            artifact_id=self._artifact_id,
            run_id=self._run_id,
            output_ref=self._output_ref,
            kind=self._kind,
            content=self._content,
            version=self._version,
            status=self._status,
            supersedes_ref=self._supersedes_ref,
        )

    def apply_transition(self, to: ArtifactStatus) -> None:
        """Apply a guarded status transition against the allowed-transitions table (ADR-0006 §4).

        Any edge outside the table raises ``InvalidArtifactTransitionError`` and leaves the status
        unchanged — including superseding a terminal version (ADR-0019 §3). The cross-entity gates
        (Human Review, QA, and "superseded only by a successor version") belong to the Run root, not
        here: the Artifact entity stays unaware of reviews, evaluations and its successor.
        """
        if to not in _ALLOWED_ARTIFACT_TRANSITIONS[self._status]:
            raise InvalidArtifactTransitionError(
                f"transition {self._status} -> {to} is not allowed"
            )
        self._status = to
